name: Node.js CI and Deploy

on:
  push:
    branches: ['master']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: client
        run: npm install

      - name: Build production
        if: github.ref == 'refs/heads/master'
        working-directory: client
        run: npm run build-production

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Remove old build artifacts
        run: |
          sshpass -p '${{ secrets.SERVER_PASSWORD }}' \
          ssh -tt -p 2222 -o StrictHostKeyChecking=no \
          henri@${{ secrets.SERVER_IP }} \
          'sudo rm -rf /var/www/game-client && sudo mkdir -p /var/www/game-client'


      - name: Transfer Build Artifacts
        run: |
          sshpass -p '${{ secrets.SERVER_PASSWORD }}' \
          scp -P 2222 -o StrictHostKeyChecking=no \
          -r dist/* \
          henri@${{ secrets.SERVER_IP }}:/var/www/game-client/
